---

- hosts: network-setup
  become: yes
  roles:
    - { role: env-setup/cpupower, tags: cpupower }
    - { role: network-setup/grub, when: default_hugepagesz == '1G' or sriov == 'true'}
    - { role: network-setup/dpdk, when: ovs_type == 'dpdk', tags: dpdk }
    - { role: network-setup/dpdk-ovs, when: ovs_type == 'dpdk', tags: dpdk-ovs }
    - { role: network-setup/check-all, when: ovs_type == 'dpdk', tags: dpdk-ovs }

- hosts: k8s-cluster:children
  roles:
    - common

- hosts: kube-master
  roles:
    - precheck
    - master

- hosts: k8s-cluster:children
  roles:
    - node

- import_playbook: kubespray/cluster.yml

- hosts: kube-master
  roles:
    - { role: k8s-setting/taint, when: taint_enabled == 'true', tags: taint }
