---

- hosts: network-setup
  become: yes
  roles:
    - { role: env-setup/cpupower, tags: cpupower }
    - { role: network-setup/grub, when: default_hugepagesz == '1G' or sriov == 'true'}
    - { role: network-setup/dpdk, when: ovs_type == 'dpdk', tags: dpdk }
    - { role: network-setup/dpdk-ovs, when: ovs_type == 'dpdk', tags: dpdk-ovs }
    - { role: network-setup/check-all, when: ovs_type == 'dpdk', tags: dpdk-ovs }


# The inventory.sample is
# [network-setup]
# X.X.X.X
# X.X.X.X

# try: `ansible-playbook -e "@inventory/group_vars/network-setup.yml" --inventory inventory/inventory.ini network-setup.yml -vvvv`
