---

- name: Get SRIOV-CNI
  shell: "{{ GOROOT }}/bin/go get -u {{ item }}"
  with_items:
    - github.com/intel/sriov-cni
  ignore_errors: True

- name: Building SRIOV-CNI
  shell: cd ~/go/src/github.com/intel/sriov-cni && make build
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"

- name: Copy sriov binary file under /opt/cni
  shell: cp /root/go/src/github.com/intel/sriov-cni/build/sriov /opt/cni/bin/sriov
