- name: install docker dependencies
  become: yes
  become_method: sudo
  apt: 
    name: "{{ item }}"
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "software-properties-common"
    - "curl"
    - "python"
    - "python-pip"
    - "python-setuptools"
    - "jq"

- name: install Helm dependencies
  become: yes
  become_method: sudo
  apt: 
    name: "{{ item }}"
  with_items:
    - "socat"
